### ISSUE TITLE
PIMD loosing sources

### ISSUE THREAD

**Issue by maximushugus** [troglobit/pimd#251]
Hello, first thanks for your work on this project.
I have a problem with PIMD on pfSense "loosing" multicast sources after a few minutes

**Description of my network setup**
I'm using PIMD on pfSense (latest version CE 2.8).
I use the official pfSense PIMD package, with PIMD version 2.3.2.
On my network I have 20 to 30 multicasts sources, with 200 Mb/s of UDP multicast traffic, on my LAN. For reference my pfSense has 192.168.3.1 on my LAN.
pfSense is connected to a network switch which is compatible with IGMP snooping.
On LAN, multicast traffic is working as expected, on a receiver I can join a multicast group.
On my switch pfSense's port is designated as a multicast router port, and all multicast traffic is routed on this port.
On pfSense, on the LAN side, it receive all those UDP multicast stream : I can confirm with packet captures.

Here is my pimd.conf file (lagg0.3 is my LAN, other laggs are other VLANs and tun_wg are wireguard links)
```shell
spt-threshold interval 10
phyint lagg0.3 enable igmpv2
phyint lagg0.99 enable igmpv2
phyint lagg0.50 enable igmpv2
phyint tun_wg1 enable igmpv2
phyint tun_wg0 enable igmpv2
phyint tun_wg2 disable igmpv2
bsr-candidate lagg0.3
rp-candidate lagg0.3
        group-prefix 239.1.1.0/24
        group-prefix 224.2.127.254/32
``` 

**What I want to do**
I want to be able to route this multicast traffic on other VLAN on my network but also on VPN links (Wireguard and OpenVPN links).

**What is working**
When I start PIMD, after about 30 secondes, everything is working as expected.
```shell
pimd -r
Virtual Interface Table ======================================================
Vif  Local Address    Subnet              Thresh  Flags      Neighbors
---  ---------------  ------------------  ------  ---------  -----------------
  0  192.168.3.1      192.168.3                1  DR NO-NBR
  1  192.168.50.1     192.168.50               1  DR NO-NBR
  2  192.168.99.1     192.168.99               1  DR NO-NBR
  3  192.168.8.155    192.168.8                1  DISABLED
  4  XXX.XXX.XXX.XXX  XXX.XX.XX.XX/24          1  DISABLED
  5  10.1.0.246       10.1.0.244/30            1  DISABLED
  6  192.168.26.1     192.168.26               1  DISABLED
  7  10.0.1.11        10.0.1.11/32             1  DISABLED
  8  192.168.25.1     192.168.25               1  DR NO-NBR
  9  192.168.27.1     192.168.27               1  PIM        192.168.27.2   
 10  192.168.29.1     192.168.29               1  DISABLED
 11  192.168.3.1      register_vif0            1 

 Vif  SSM Group        Sources             

Multicast Routing Table ======================================================
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.31     224.2.127.254    192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.1        192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.2        192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.3        192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

..
..
..

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.27       192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.28       192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.29       192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.30       192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        

TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
----------------------------------- (S,G) ------------------------------------
Source           Group            RP Address       Flags
---------------  ---------------  ---------------  ---------------------------
192.168.3.152    239.1.1.31       192.168.3.1      SG
Joined   oifs: ............        
Pruned   oifs: ............        
Leaves   oifs: ............        
Asserted oifs: ............        
Outgoing oifs: ............        
Incoming     : I...........        


TIMERS:  Entry    JP    RS  Assert VIFS:  0  1  2  3  4  5  6  7  8  9  10  11
             0     0     0       0        0  0  0  0  0  0  0  0  0  0  0  0
--------------------------------- (*,*,G) ------------------------------------
Number of Groups: 32
Number of Cache MIRRORs: 0
------------------------------------------------------------------------------
``` 

At this moment if I join one of this mutlicast on other VLAN (for example 192.168.50.0/24), the multicast group is routed to the receiver as expected.

**What is not working**
After about 1 min, I gradually see that PIMD is not "receiving" multicast groups. At the beginning it sees 32 groups, then  10 and after a few minutes 0.
During this periode, nothing is changing on my configuration.
I do not see any error on the logs.
There is no multicast routing for those groups.
I can confirm pfSense is still receiving those mutlicasts groups (packet capture).
I tried disabling the firewall but it didn't change anything

Do you have an idea on what is causing PIMD to gradually "loose" track of incoming mutlicast groups in about 2 minutes ?
Thanks

**Comment by troglobit** [comment]
Thank you for the extensive report!

Version 2.3.2 of pimd is very old, and even though it's the latest official release of the project, it is so far behind the `master` branch.  It is very likely your issue is already solved but I cannot point to a single commit or other (fixed) bug report that addresses your specific problem.

Unfortunately I'm no longer actively working on pimd, there is simply not enough interest or funding for me to do so. I would have liked very much to release pimd 3, but at this time it just doesn't seem likely.

**Comment by maximushugus** [comment]
Thanks for your answer.
I did a lot of testing, including running PIMD 2.3.2 on my Arch Linux computer on my LAN with exact same problem. So I think this is a problem with PIMD.
I will try to compile PIMD from master branch on this Arch Linux computer and I will do an update here to see if it solve this problem.

**Comment by maximushugus** [comment]
ok @troglobit as you said, running latest master branch version, it looks it solve this problem !
```shell
udo pimctl 
                                                                                                                                                            
PIM Interface Table
Interface         State     Address            Priority  Hello  Nbr  DR Address      DR Priority                                                            
tb4               Up        192.168.3.131             1     30    1  192.168.3.131             1
                                                                                                                                                            
PIM Neighbor Table
Interface         Address            Priority  Mode  Uptime/Expires                                                                                         
tb4               192.168.3.1               1        0h5m12s/0h1m30s             
                                                                                                                                                            
Multicast Routing Table
Source            Group            RP Address       Flags                                                                                                   
ANY               224.0.1.75       192.168.3.131    WC RP
192.168.3.31      224.2.127.254    192.168.3.1      SG
192.168.3.152     239.1.1.1        192.168.3.1      SG
192.168.3.152     239.1.1.2        192.168.3.1      SG
192.168.3.152     239.1.1.3        192.168.3.1      SG
192.168.3.152     239.1.1.4        192.168.3.1      SG
192.168.3.152     239.1.1.5        192.168.3.1      SG
192.168.3.152     239.1.1.6        192.168.3.1      SG
192.168.3.152     239.1.1.7        192.168.3.1      SG
192.168.3.152     239.1.1.8        192.168.3.1      SG
192.168.3.152     239.1.1.9        192.168.3.1      SG
192.168.3.152     239.1.1.10       192.168.3.1      SG
192.168.3.152     239.1.1.12       192.168.3.1      SG
192.168.3.152     239.1.1.13       192.168.3.1      SG
192.168.3.152     239.1.1.14       192.168.3.1      SG
192.168.3.152     239.1.1.15       192.168.3.1      SG
192.168.3.152     239.1.1.16       192.168.3.1      SG
192.168.3.152     239.1.1.17       192.168.3.1      SG
192.168.3.152     239.1.1.18       192.168.3.1      SG
192.168.3.152     239.1.1.19       192.168.3.1      SG
192.168.3.152     239.1.1.20       192.168.3.1      SG
192.168.3.152     239.1.1.21       192.168.3.1      SG
192.168.3.152     239.1.1.23       192.168.3.1      SG
192.168.3.152     239.1.1.24       192.168.3.1      SG
192.168.3.152     239.1.1.25       192.168.3.1      SG
192.168.3.152     239.1.1.26       192.168.3.1      SG
192.168.3.152     239.1.1.27       192.168.3.1      SG
192.168.3.152     239.1.1.28       192.168.3.1      SG
192.168.3.152     239.1.1.29       192.168.3.1      SG
192.168.3.152     239.1.1.30       192.168.3.1      SG
192.168.3.152     239.1.1.31       192.168.3.1      SG
192.168.3.152     239.1.1.44       192.168.3.1      SG
192.168.3.152     239.1.1.77       192.168.3.1      SG
ANY               239.255.255.250  192.168.3.131    WC RP
192.168.3.18      239.255.255.250  192.168.3.131    SPT CACHE SG
192.168.3.21      239.255.255.250  192.168.3.131    SPT CACHE SG

Number of Groups        : 34
Number of Cache MIRRORs : 2
                                                                                                                                                            
PIM Candidate Rendez-Vous Point Table
Group Address     RP Address       Prio  Holdtime  Expires                                                                                                  
224.0.0.0/4       192.168.3.131      20        75  0h1m10s
224.2.127.254/32  192.168.3.1         0       150  0h2m25s
232.0.0.0/8       169.254.0.1         1   Forever  Never

Current BSR address: 192.168.3.131
                                                                                                                                                            
PIM Rendez-Vous Point Set Table
Group Address     RP Address       Prio  Holdtime  Type                                                                                                     
232.0.0.0/8       169.254.0.1         1   Forever  Static 
224.0.0.0/4       192.168.3.131      20        70  Dynamic
239.1.1.0/24      192.168.3.1         0       145  Dynamic
224.2.127.254/32  192.168.3.1         0       145  Dynamic

```

**Comment by maximushugus** [comment]
I built PIMD 3.0beta1 for my pfSense box.
Running pimd with this config : 
```shell
spt-threshold infinity
phyint lagg0.3 enable
phyint lagg0.99 enable
phyint lagg0.50 enable
phyint tun_wg1 disable
phyint tun_wg2 disable
bsr-candidate lagg0.3
rp-candidate lagg0.3
        group-prefix 239.1.1.0/24
        group-prefix 224.2.127.254/32
``` 

I still have the problem.
What is really weird is that multicast groups always disappeare in the same order : 
```shell
Multicast Routing Table
Source            Group            RP Address       Flags                                           
192.168.3.31      224.2.127.254    192.168.3.1      SPT SG
192.168.3.152     239.1.1.1        192.168.3.1      SG
192.168.3.152     239.1.1.2        192.168.3.1      SG
192.168.3.152     239.1.1.3        192.168.3.1      SG
192.168.3.152     239.1.1.5        192.168.3.1      SG
192.168.3.152     239.1.1.6        192.168.3.1      SG
192.168.3.152     239.1.1.7        192.168.3.1      SG
192.168.3.152     239.1.1.8        192.168.3.1      SG
192.168.3.152     239.1.1.9        192.168.3.1      SG
192.168.3.152     239.1.1.10       192.168.3.1      SG
192.168.3.152     239.1.1.12       192.168.3.1      SG
192.168.3.152     239.1.1.13       192.168.3.1      SG
192.168.3.152     239.1.1.14       192.168.3.1      SG
192.168.3.152     239.1.1.15       192.168.3.1      SG
192.168.3.152     239.1.1.16       192.168.3.1      SG
192.168.3.152     239.1.1.17       192.168.3.1      SG
192.168.3.152     239.1.1.18       192.168.3.1      SG
192.168.3.152     239.1.1.19       192.168.3.1      SG
192.168.3.152     239.1.1.20       192.168.3.1      SG
192.168.3.152     239.1.1.21       192.168.3.1      SG
192.168.3.152     239.1.1.23       192.168.3.1      SG
192.168.3.152     239.1.1.24       192.168.3.1      SG
192.168.3.152     239.1.1.25       192.168.3.1      SG
192.168.3.152     239.1.1.26       192.168.3.1      SG
192.168.3.152     239.1.1.27       192.168.3.1      SG
192.168.3.152     239.1.1.77       192.168.3.1      SG

Number of Groups        : 26

``` 

then 

```shell
Multicast Routing Table
Source            Group            RP Address       Flags                                           
192.168.3.31      224.2.127.254    192.168.3.1      SPT SG
192.168.3.152     239.1.1.6        192.168.3.1      SG
192.168.3.152     239.1.1.12       192.168.3.1      SG
192.168.3.152     239.1.1.14       192.168.3.1      SG
192.168.3.152     239.1.1.15       192.168.3.1      SG
192.168.3.152     239.1.1.16       192.168.3.1      SG
192.168.3.152     239.1.1.20       192.168.3.1      SG
192.168.3.152     239.1.1.27       192.168.3.1      SG

Number of Groups        : 8
Number of Cache MIRRORs : 0

``` 

and 4 groups and 1 and 0.

I really don't understand what's happening.

**Comment by troglobit** [comment]
Thank you for the thorough testing with master.  I really appreciate the detailed reports.

As mentioned before, I'm unfortunately not able to actively maintain pimd.  This includes investigating or troubleshooting issues, I simply don't have the bandwidth to do so properly.

If you're able to work around the issues or if anyone wants to submit patches, that might change things on my end. Otherwise I want to be upfront that any further engagement from me is unlikely.

Thanks again for your interest in the project.

**Comment by maximushugus** [comment]
> As mentioned before, I'm unfortunately not able to actively maintain pimd. This includes investigating or troubleshooting issues, I simply don't have the bandwidth to do so properly.
> 
> If you're able to work around the issues or if anyone wants to submit patches, that might change things on my end. Otherwise I want to be upfront that any further engagement from me is unlikely.

I know, no problem.
I write here to document this issue.
If at some point you or anybody has the time to give ideas while I progress my troubleshooting it is great.



So here are other tests I did on my network : 

1. On another pfSense : 
I installed pfSense on another VM on another port on my switch, to see if the problem comes from my specific pfSense main router. I installed a fresh pfSense 2.8.0 CE, then installed PIMD 2.3.2 with exact same problem as here : after some time, PIMD doesn't see multicast groups while I can see these groups are forwarded to the VM in tcpdump, from my switch (IGMP snooping). I also tried installing PIMD 3.0beta1, with the same results.

**So this is not my pfSense's configuration which is the source of this problem**

2. I installed PIMD 2.3.2 on a fresh **Debian** VM on another port on my switch. I**t looks as if this time PIMD see the sources groups without a limit in time** but looks "unstable" as  it drops to 0 the number of sources from time to time and a few seconds after it goes back to seeing every groups. I have to test to compile PIMD 3.0beta1 on this VM to see if it's better.

**But after installing this PIMD 2.3.2 on this VM I can see a changing behavior on my pfSense**
PIMD on pfSense and PIMD on this Debian VM are on the same network subnet, and see each other as PIM neighbor.
When PIMD on my pfSense sees the other PIMD on Debian, it doesn't loose the multicasts groups sources for a long time if at all.
As if seeing another PIM neighbor triggered something in the code to update the source list.
I did not see this behavior with another PIMD on a distant router (PIM on FRR) through a Wireguard tunnel. It looks as if it has to be on the same subnet/network

3. I tried looking at the multicast config on pfSense/FreeBSD : 
While PIMD doesn't see multicast sources after some time, here are the result of 

```shell
netstat -g

IPv4 Virtual Interface Table
 Vif   Thresh   Local-Address   Remote-Address    Pkts-In   Pkts-Out
  0         1   192.168.3.1                             0          0
  1         1   192.168.3.1                             0          0
  2         1   192.168.50.1                            0          0
  3         1   192.168.99.1                            0          0
  4         1   192.168.27.1                            0          0

IPv4 Multicast Forwarding Table
 Origin          Group             Packets In-Vif  Out-Vifs:Ttls
 192.168.3.152   239.1.1.16              0  65535   
 192.168.3.152   239.1.1.1               0  65535   
 192.168.3.152   239.1.1.17              0  65535   
 192.168.3.152   239.1.1.2               0  65535   
 192.168.3.152   239.1.1.18              0  65535   
 192.168.3.152   239.1.1.3               0  65535   
 192.168.3.152   239.1.1.19              0  65535   
 192.168.3.152   239.1.1.4               0  65535   
 192.168.3.152   239.1.1.20              0  65535   
 192.168.3.152   239.1.1.5               0  65535   
 192.168.3.152   239.1.1.21              0  65535   
 192.168.3.152   239.1.1.22              0  65535   
 192.168.3.152   239.1.1.6               0  65535   
 192.168.3.152   239.1.1.23              0  65535   
 192.168.3.152   239.1.1.7               0  65535   
 192.168.3.152   239.1.1.8               0  65535   
 192.168.3.152   239.1.1.24              0  65535   
 192.168.3.152   239.1.1.25              0  65535   
 192.168.3.152   239.1.1.9               0  65535   
 192.168.3.152   239.1.1.10              0  65535   
 192.168.3.152   239.1.1.26              0  65535   
 192.168.3.152   239.1.1.11              0  65535   
 192.168.3.152   239.1.1.12              0  65535   
 192.168.3.152   239.1.1.77              0  65535   
 192.168.3.152   239.1.1.13              0  65535   
 192.168.3.152   239.1.1.14              0  65535   
 192.168.3.152   239.1.1.30              0  65535   
 192.168.3.152   239.1.1.15              0  65535   


IPv6 Multicast Interface Table is empty

IPv6 Multicast Forwarding Table is empty

``` 

This is the sme result befor and after PIMD looses sight of sources.

and 
```shell
ifmcstat
....

//// other network interfaces

lagg0.3:
        inet 192.168.3.1
        igmpv2
                group 224.0.0.22 mode exclude
                        mcast-macaddr 01:00:5e:00:00:16
                group 224.0.0.2 mode exclude
                        mcast-macaddr 01:00:5e:00:00:02
                group 224.0.0.13 mode exclude
                        mcast-macaddr 01:00:5e:00:00:0d
                group 224.0.0.251 mode exclude
                        mcast-macaddr 01:00:5e:00:00:fb
        inet6 fe80::225:90ff:fe9c:5644%lagg0.3 scopeid 0xd
        mldv2 flags=2<USEALLOW> rv 2 qi 125 qri 10 uri 3
                group ff02::fb%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:00:00:00:fb
                group ff02::2%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:00:00:00:02
        inet 192.168.3.1
        igmpv2
                group 224.0.0.1 mode exclude
                        mcast-macaddr 01:00:5e:00:00:01
        inet6 fe80::225:90ff:fe9c:5644%lagg0.3 scopeid 0xd
        mldv2 flags=2<USEALLOW> rv 2 qi 125 qri 10 uri 3
                group ff02::1:ff00:1%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:ff:00:00:01
                group ff01::1%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:00:00:00:01
                group ff02::2:1861:20ce%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:18:61:20:ce
                group ff02::2:ff18:6120%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:ff:18:61:20
                group ff02::1%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:00:00:00:01
                group ff02::1:ff9c:5644%lagg0.3 scopeid 0xd mode exclude
                        mcast-macaddr 33:33:ff:9c:56:44

``` 

again same result before and after the problem.

So it looks as if pfSense / FreeBSD 15 is seeing multicast sources correctly.

4. **It looks as of the problem always happen after the same amount of time PIMD starts** : 
When I start PIMD, it sees multicast sources after 60 seconds
**It sees every sources groups until exactly 3 minutes and 20 seconds**. Then it start loosing sight of groups, always in the same order, with 239.1.1.11  239.1.1.12    239.1.1.14    239.1.1.15    239.1.1.16    239.1.1.30     239.1.1.78 staying for a few more minutes before disappearing also.



I will try to look at the code but I'm not a dev so it's difficult for me.
If those tests (keeping sources while another PIMD neighbor is on the same subnet and problemn happening after 3min20sec) make someone think of a particular problem, help would be appreciated.

Thanks

**Comment by maximushugus** [comment]
I also noticed that while running PIMD, I have a lot of "multicast forwarding cache misses", "upcall queue overflows" and "datagrams with no route for origin" : 
```shell
netstat -gs
IPv4 multicast forwarding:
        2278037406 multicast forwarding cache lookups
        2254920579 multicast forwarding cache misses
        265672 upcalls to multicast routing daemon
        2254114108 upcall queue overflows
        0 upcalls dropped due to full socket buffer
        262669 cache cleanups
        2254920579 datagrams with no route for origin
        0 datagrams arrived with bad tunneling
        0 datagrams could not be tunneled
        132033 datagrams arrived on wrong interface
        0 datagrams selectively dropped
        0 datagrams dropped due to queue overflow
        0 datagrams dropped for being too large
IPv6 multicast forwarding:
        0 multicast forwarding cache lookups
        0 multicast forwarding cache misses
        0 upcalls to multicast routing daemon
        0 upcall queue overflows
        0 upcalls dropped due to full socket buffer
        0 cache cleanups
        0 datagrams with no route for origin
        0 datagrams arrived with bad tunneling
        0 datagrams could not be tunneled
        0 datagrams arrived on wrong interface
        0 datagrams selectively dropped
        0 datagrams dropped due to queue overflow
        0 datagrams dropped for being too large
``` 
As soon as I stop PIMD, I do not have this rising even if I'm still receiving the multicasts groups for a few minutes (the time my switch remove pfSense's port as a multicast router port)

What does "multicast forwarding cache misses", "upcall queue overflows" and "datagrams with no route for origin" mean ? Is this a PIMD problem or a pfSense / FreeBSD problem ?

**Comment by maximushugus** [comment]
Here are the logs of pimd 3.0-beta1 running on pfSense (CE 2.8.0 so FressBSD 15-CURRENT based) : 

[log.txt](https://github.com/user-attachments/files/20691833/log.txt)

The problem happen arround 13:34:47, as you can sse before it sees every multicast groups, and after only 8 of them.
I don't see any errors that could indicate what is the problem


**To add another test : I built PIMD from sources v3.0-beta1 on a Debian VM : the problem doesn't happen !!**
Running pimctl -m I can see "Number of Groups" jumping from 30 to 0 but always gonging back to 30 contrary to pfSense.
So maybe this is a FreeBSD / pfSense specific problem.
I can see in the code that there are some diffence if running on Linux or other BSD systems. Maybe it can point in the right direction

**Comment by maximushugus** [comment]
To update on this problem, I did some testing with 2 VM on my Network, installing iperf (not iperf3) and testing multicast communication in beetwen. 

Doing this i discovered that for the multicast address used by iperf (testing for example with 239.1.1.1), PIMD on my pfSense didn't loose the source. 
But in pimctl I see this source as this with 2 lines and the flag as seen below 
```shell
Multicast Routing Table
===============================================================================
Source            Group            RP Address       Flags 
===============================================================================
ANY               239.1.1.1        192.168.3.1      WC RP
192.168.3.152     239.1.1.1        192.168.3.1      SPT CACHE SG
``` 
As you can see this is not the same as in previous responses above where I only got 1 line per source and with only "SG" flag.
By the way I don't know what these flags means.

Also on my network switch (EdgeSwitch ES-16-XG), doing so i can the source on the multicast forwarding database : 
```shell

VLAN ID | MAC Address | Component | Type | Description | Interface(s) | Forwarding Interface(s)
-- | -- | -- | -- | -- | -- | --

3 | 01:00:5E:01:01:01 | IGMP | Dynamic | Network Assist | 3/1, 3/2 | 3/1, 3/2

``` 
It was not the case previously but I still received the multicast sources on my pfsense as the port on the switch was detected as a mrouter port and forwarded all multicast traffic.



So to overcome the issue, on my multicast server running Debian (the one streaming my multicast streams), I added this configuration : 

1. Modify `/etc/sysctl.conf ` file and adding `net.ipv4.igmp_max_memberships = 100` to overcome the max number of GMP memberships (by default 20)
2. For each multicast source I stream I do `ip addr add 239.X.X.X/24 dev eth0 autojoin` (I did a startup script adding all of my sources)

So now the server is joining it's own multicast sources and PIMD doesn't loose sight of those.

I don't think this is supposed to work this way @troglobit 
For me the problem comes either from a bug in PIMD on pfSense (the most probable), or a bug in the multicast implementation in my network swith (unlikely as i said i'm still receiving the mutlicast groups from tcpdump on pfSense) or a problem in my multicast server config (dvblast). 
But with this workaround it works.
